# Auto-generated by scripts/bootstrap-sqs.sh — no editar a mano.
bootstrap = {
  sqs = {
    queue_url = "http://localhost:4566/000000000000/fundoflow-local-sync"
    queue_arn = "arn:aws:sqs:us-east-1:000000000000:fundoflow-local-sync"
    dlq_url   = "http://localhost:4566/000000000000/fundoflow-local-sync-dlq"
    dlq_arn   = "arn:aws:sqs:us-east-1:000000000000:fundoflow-local-sync-dlq"
  }
}
