#!/usr/bin/env bash
# Crea la cola principal y la DLQ de sincronización en LocalStack usando
# boto3 desde el container (más confiable que awslocal para atributos con JSON).
#
# Después de crear las colas, genera terraform.auto.tfvars con los ARNs y URLs
# para que Terraform los exponga como outputs sin tener que gestionar SQS.

set -euo pipefail

PREFIX="${NAME_PREFIX:-fundoflow-local}"
REGION="${AWS_DEFAULT_REGION:-us-east-1}"
CONTAINER="${CONTAINER:-fundoflow-localstack}"
TFVARS_FILE="${TFVARS_FILE:-terraform.auto.tfvars}"
ENDPOINT="${ENDPOINT:-http://localhost:4566}"

green() { printf "\033[32m%s\033[0m\n" "$*"; }
red()   { printf "\033[31m%s\033[0m\n" "$*"; }
title() { printf "\n\033[1;34m== %s ==\033[0m\n" "$*"; }

if ! docker ps --format '{{.Names}}' | grep -qx "$CONTAINER"; then
  red "Container $CONTAINER is not running. Run: make up"
  exit 1
fi

create_queues() {
  docker exec -i "$CONTAINER" \
    env AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test \
         AWS_DEFAULT_REGION="$REGION" \
         ENDPOINT="$ENDPOINT" \
         PREFIX="$PREFIX" \
    python3 <<'PY'
import os, json, boto3

endpoint  = os.environ["ENDPOINT"]
region    = os.environ["AWS_DEFAULT_REGION"]
prefix    = os.environ["PREFIX"]

sqs = boto3.client("sqs", endpoint_url=endpoint, region_name=region)

# 1) DLQ
dlq_name = f"{prefix}-sync-dlq"
r = sqs.create_queue(QueueName=dlq_name, Attributes={"MessageRetentionPeriod": "1209600"})
dlq_url = r["QueueUrl"]
dlq_arn = sqs.get_queue_attributes(QueueUrl=dlq_url, AttributeNames=["QueueArn"])["Attributes"]["QueueArn"]

# 2) Main queue con redrive a DLQ
main_name = f"{prefix}-sync"
redrive = {"deadLetterTargetArn": dlq_arn, "maxReceiveCount": 3}
r = sqs.create_queue(
  QueueName=main_name,
  Attributes={
    "VisibilityTimeout": "120",
    "RedrivePolicy": json.dumps(redrive),
  },
)
main_url = r["QueueUrl"]
main_arn = sqs.get_queue_attributes(QueueUrl=main_url, AttributeNames=["QueueArn"])["Attributes"]["QueueArn"]

# Imprime un JSON que el bash parsea
out = {
  "dlq_url": dlq_url,
  "dlq_arn": dlq_arn,
  "queue_url": main_url,
  "queue_arn": main_arn,
}
print(json.dumps(out))
PY
}

title "Create queues via boto3"
RAW=$(create_queues)

DLQ_URL=$(echo "$RAW"   | python3 -c 'import sys,json; print(json.load(sys.stdin)["dlq_url"])')
DLQ_ARN=$(echo "$RAW"   | python3 -c 'import sys,json; print(json.load(sys.stdin)["dlq_arn"])')
Q_URL=$(echo "$RAW"     | python3 -c 'import sys,json; print(json.load(sys.stdin)["queue_url"])')
Q_ARN=$(echo "$RAW"     | python3 -c 'import sys,json; print(json.load(sys.stdin)["queue_arn"])')

green "DLQ url : $DLQ_URL"
green "DLQ arn : $DLQ_ARN"
green "Queue url: $Q_URL"
green "Queue arn: $Q_ARN"

title "Write ${TFVARS_FILE}"
TFVARS_PATH="$(cd "$(dirname "$0")/.." && pwd)/terraform/${TFVARS_FILE}"
cat > "$TFVARS_PATH" <<EOF
# Auto-generated by scripts/bootstrap-sqs.sh — no editar a mano.
bootstrap = {
  sqs = {
    queue_url = "$Q_URL"
    queue_arn = "$Q_ARN"
    dlq_url   = "$DLQ_URL"
    dlq_arn   = "$DLQ_ARN"
  }
}
EOF
green "Wrote $TFVARS_PATH"

title "Verify"
docker exec -i "$CONTAINER" \
  env AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test \
       AWS_DEFAULT_REGION="$REGION" \
  awslocal sqs list-queues 2>/dev/null | grep -v '^INFO' | sed 's/^/  /'

green "SQS bootstrap complete."
